[package]
name = "giortes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
giortes-lib = { path = "giortes-lib" }
env_logger = "0.9.0"
actix-web = "4.0.1"
serde_json = "1.0.79"
log = "0.4.16"
tokio = { version = "1", features = ["full"] }
tokio-cron-scheduler = "0.6.2"
rss = "2.0"
